### ISSUE TITLE
Rotate not working in IE8

### ISSUE THREAD

**Issue by whatever6453** [louisremi/jquery.transform.js#20]
The rotate transform isn't working for me in IE8. It does work in IE9 and FireFox.

Example here: http://jsfiddle.net/E9vfj/

I had to inline jquery.transform.js to get it to work in the fiddle. This isn't necessary outside the fiddle.

**Comment by whatever6453** [comment]
I did a little investigation of this. AFAICT, the correct IE/matrix specific code paths are being followed.
So I currently suspect that the matrix values are incorrect.
But I need to brush up on my matrix algebra before being able to confirm this.

I'll see if randomly fiddling with the order of application of transforms has any effect.

**Comment by louisremi** [comment]
Wow, too bad I didn't take time to look at this issue earlier. 

There seems to be two important problems I wasn't aware of in the current script.
The first one is that it is impossible to use rotate, scale or skew on inline or inline-block elements in IE8 (because the zoom trick to force layout doesn't work in standard mode).
The second one is that the script breaks in IE678 at line 172 :-(

Will investigate, thanks.

**Comment by louisremi** [comment]
Can you confirm that you are not having this problem with block elements in IE8, using the latest version of the script?

**Comment by louisremi** [comment]
Marking as fixed, please tell me if you're still seeing this problem.
